name: Node.js CI

on:
  push:
    branches: [ dev-mohamed ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Redis
      run: sudo apt-get install -y redis-server

      - name: Start Redis Server
        run: sudo service redis-server start

      - name: Install Dependencies
        run: cd user-api && npm ci

      - run: cd user-api && npm run build --if-present
      
      - name: Test Application
        run: cd user-api && npm test
